HOVER_MAP = {'token': True,
             'lemma': True,
             'prediction': True,
             'subtype': True,
             'amyloid_detail': False,
             'csf': False,
             'weight': True,
             'context': True,
             'weight_norm': False,
             'Y': False,
             'X': False,
             'Z': False,
             'alt_pos': True}

NAME_MAP = {'ADJ': 'Adjectives',
            'ADP': 'Adpositions',
            'ADV': 'Adverbs',
            'AUX': 'Auxiliaries',
             'CONJ': 'Conjunctions',
             'CCONJ': 'Coordinating conjunctions',
             'DET': 'Determiners',
             'INTJ': 'Interjections',
             'NOUN': 'Nouns',
             'NUM': 'Numerals',
             'PART': 'Particles',
             'PRON': 'Pronouns',
             'PROPN': 'Proper nouns',
             'PUNCT': 'Punctuation',
             'SCONJ': 'Subordinating conjunctions',
             'SYM': 'Symbols',
             'VERB': 'Verbs',
             'X': 'other',
             'SPACE': 'spaces',
             'EX': "Existential 'there'"}

CAT_MAP = {"AMYLOID_NEG": "Amyloid negative", "AMYLOID_POS": "Amyloid positive"}
